### ISSUE TITLE
No 404

### ISSUE THREAD

**Issue by 0x80** [bntzio/gatsby-starter-superstylin#1]
Invalid routes are not caught it seems. The 404 doesn't display.

**Comment by bntzio** [comment]
@0x80 Oh that's true, I'll fix that tomorrow, thank you! 👍

**Comment by bntzio** [comment]
@0x80 it's done! https://github.com/bntzio/gatsby-starter-superstylin/commit/bd87f3c8f8e3d468d24bb9992cbd44eb72504bec
