### ISSUE TITLE
hedron styles not rendered

### ISSUE THREAD

**Issue by jesnil01** [bntzio/gatsby-starter-superstylin#2]
There seems to be some styles that don't render in the build process. Eg. hedron does not seem to work.

It's apparent on the About page as the content jumps as the javascript styles is getting loaded:
https://superstylin.netlify.com/about/

Tried to fix it but with no success. Any solution to this?

**Comment by bntzio** [comment]
@jesnil01 Sorry for the late reply! Yeah, I got a fix, it's a little bit hacky but I'm going to implement it right now 😄

**Comment by bntzio** [comment]
Here's the fix 👉 c9ab58f50b257c8a5b552a9f5271b2437439e124
