### ISSUE TITLE
Cannot develop

### ISSUE THREAD

**Issue by gnerzhin** [bntzio/gatsby-starter-superstylin#5]
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Сергей\Documents\GitHub\my-blog/html'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)

**Comment by bntzio** [comment]
@gnerzhin did u fix the prob? what was it?

**Comment by gnerzhin** [comment]
Nah, it seems i have problems with Gatsby itself. So now trying to fix it 3:
